export const NOTION_TITLE_PROPERTY_NAME = process.env.NEXT_PUBLIC_NOTION_TITLE_PROPERTY_NAME;
export const NOTION_ENTRY_PAGE_TITLE = process.env.NEXT_PUBLIC_NOTION_ENTRY_PAGE_TITLE;
export const NOTION_DATA_BASE_ID = process.env.NEXT_PUBLIC_NOTION_DATABASE_ID;
export const NOTION_KEY = process.env.NEXT_PUBLIC_NOTION_KEY;
